### ISSUE TITLE
Can't complete Cron Job when python code is embed (through reticulate) inside the R script

### ISSUE THREAD

**Issue by nicocriscuolo** [bnosac/cronR#34] opened 2021-04-01 21:23 UTC
I've created an R script that first launches a python script through the `py_run_file()` function and then executes some R code. I need to schedule the launch of such script at a certain hour of the day, and hence I used the package `cronR`. Unfortunately, when I call the script function **just as a cron job**, the job freezes and doesn't end. Here's a reproducible example:

```R

library(reticulate)

today <- Sys.Date()

print(today)

use_python("/Users/nicocriscuolo/miniconda3/bin/python3.8",
           required = TRUE)

print("The function 'use_python()' works!")

py_run_file("/Users/nicocriscuolo/Desktop/test.py")

print(paste("Cron job ended on the ",
            today))
``` 

This is the content of the `test.py` file:

```python
print("python script!")
```

Do you have any suggestion? Thanks a lot for your help!

**Comment by jwijffels** [comment] 2021-04-01 21:37
My advice would be. Don't use `~`, use the full path.

**Comment by nicocriscuolo** [comment] 2021-04-02 08:13
Thanks for your prompt answer. Unfortunately, this didn't solve the issue. I would like to specify that the problem occurs just with the `py_run_file()` function. Is there something else I could try?

**Comment by jwijffels** [comment] 2021-04-02 08:15
look at the logs of the script

**Comment by nicocriscuolo** [comment] 2021-04-02 08:16
The generated file is completely empty. I tried from another machine and the logs were empty too.

**Comment by jwijffels** [comment] 2021-04-02 08:17
make it print out something so that you at least see where it failed

**Comment by nicocriscuolo** [comment] 2021-04-02 08:31
Just updated the code above. The problem appears when running the `py_run_file()`. Here's a screenshoot of the logs:

<img width="851" alt="Screenshot 2021-04-02 at 10 31 15" src="https://user-images.githubusercontent.com/35098432/113398287-a35f9c00-939e-11eb-95bc-48e7a8dc22ba.png">

**Comment by jwijffels** [comment] 2021-04-02 08:36
Did you check if "/Users/nicocriscuolo/Desktop/test.py" exists and does it run python2 / python3 which has a different print syntax

**Comment by nicocriscuolo** [comment] 2021-04-02 08:44
I confirm that the test.py script exists. Infact, when I run it manually from R everything works, as you can see this screenshot of the RStudio console:

<img width="484" alt="Screenshot 2021-04-02 at 10 40 58" src="https://user-images.githubusercontent.com/35098432/113399168-0b62b200-93a0-11eb-8f53-0d3a52ef35cd.png">

As for python, my code runs on python 3, as you can see from the screenshot of the spyder console (please check bottom right). In spyder, I set the "miniconda" folder, which is the same I use in the R command `use_python()`.

<img width="1430" alt="Screenshot 2021-04-02 at 10 39 48" src="https://user-images.githubusercontent.com/35098432/113399314-4fee4d80-93a0-11eb-9754-21721e18fa6c.png">

**Comment by jwijffels** [comment] 2021-04-02 08:50
I have no idea what the cause of it is. 
As the cron job has run, it is not related to cron itself but probably related to reticulate and how it probably has set up some environment variables or whatever in your RStudio environment which you aren't aware exist. 
You could check print(Sys.getenv()) to see where there is a difference between your RStudio environment and a normal R shell

**Comment by jwijffels** [comment] 2021-04-02 15:01
I'm closing this as the issue is related to reticulate, not the cronR package

**Closed by jwijffels** 2021-04-02 15:01 UTC
