### ISSUE TITLE
cronR addin not working. Error on startup

### ISSUE THREAD

**Issue by tamilvanan7** [bnosac/cronR#57] opened 2022-10-27 21:53 UTC
**My environment:
R - v4.0.3
Rstudio - v1.4.1717-3
Shiny - v1.7.3
ShinyFiles - v0.9.3
miniUI - v0.1.1.1**

**When I try to use the Addins -> Scehdule R scripts on Linux / Unix,**

**The console shows that it's trying to run the Addin. But fails.**

> cronR:::cron_rstudioaddin()

**Even when I try to run the command, cronR::cron_rstudioaddin(RscriptRepository = Sys.getenv("CRON_LIVE", unset = getwd())), I still get the same error. I've also properly set the CRON_LIVE environment variable before running this command** 

Loading required namespace: shiny
Loading required namespace: miniUI
Loading required namespace: shinyFiles
Error in `vec_as_location()`:
! `...` must be empty.
✖ Problematic argument:
• call = call
Run `rlang::last_error()` to see where the error occurred.
> cronR:::cron_rstudioaddin()
Error in `vec_as_location()`:
! `...` must be empty.
✖ Problematic argument:
• call = call
Run `rlang::last_error()` to see where the error occurred.

**When I run rlang::last_error() I get the following**

<error/rlib_error_dots_nonempty>
Error in `vec_as_location()`:
! `...` must be empty.
✖ Problematic argument:
• call = call
---
Backtrace:
  1. cronR:::cron_rstudioaddin()
 18. shiny::icon("cloud-upload")
 19. fontawesome::fa_i(name = name, class = class, ...)
 20. fontawesome:::get_icon_idx(...)
 21. fontawesome:::get_icon_idx_all_types(name = name)
 23. tibble:::`[.tbl_df`(...)
 24. tibble:::vectbl_as_col_location(...)
 27. vctrs::vec_as_location(j, n, names, call = call)

**When I run rlang::last_trace(), I'm getting the following dump**

<error/rlib_error_dots_nonempty>
Error in `vec_as_location()`:
! `...` must be empty.
✖ Problematic argument:
• call = call
---
Backtrace:
     ▆
  1. └─cronR:::cron_rstudioaddin()
  2.   ├─miniUI::miniPage(...)
  3.   │ ├─htmltools::attachDependencies(...)
  4.   │ ├─htmltools::tagList(...)
  5.   │ │ └─rlang::dots_list(...)
  6.   │ ├─shiny::fillPage(...)
  7.   │ │ └─shiny::bootstrapPage(...)
  8.   │ │   └─rlang::list2(...)
  9.   │ └─tags$div(class = "gadget-container", ...)
 10.   │   └─rlang::dots_list(...)
 11.   ├─miniUI::miniTabstripPanel(...)
 12.   │ └─miniUI:::buildTabset(list(...), "nav gadget-tabs", id = id, selected = selected)
 13.   ├─miniUI::miniTabPanel(...)
 14.   │ └─shiny::tabPanel(...)
 15.   │   └─bslib::nav(title, ..., value = value, icon = icon)
 16.   │     └─bslib:::tabPanel_(title, ..., value = value, icon = icon)
 17.   │       └─bslib:::prepTabIcon(icon)
 18.   └─shiny::icon("cloud-upload")
 19.     └─fontawesome::fa_i(name = name, class = class, ...)
 20.       └─fontawesome:::get_icon_idx(...)
 21.         └─fontawesome:::get_icon_idx_all_types(name = name)
 22.           ├─alias_tbl[alias_tbl$alias == name, "name", drop = TRUE]
 23.           └─tibble:::`[.tbl_df`(...)
 24.             └─tibble:::vectbl_as_col_location(...)
 25.               ├─tibble:::subclass_col_index_errors(...)
 26.               │ └─base::withCallingHandlers(...)
 27.               └─vctrs::vec_as_location(j, n, names, call = call)
 28.                 └─ellipsis::check_dots_empty()
 29.                   └─rlang:::action_dots(...)
 30.                     ├─base (local) try_dots(...)
 31.                     └─rlang (local) action(...)

**Comment by jwijffels** [comment] 2022-10-28 05:28
Looks like an error in fontawesome::fa_i, maybe follow this advice at https://community.rstudio.com/t/error-in-vec-as-location/149485

**Comment by jwijffels** [comment] 2022-11-08 22:22
This seems to be related to shiny and fontawesome. If I read the logs of the shiny NEWS file it now says

```
shiny 1.7.3
Bug fixes
Shiny 1.7.0 changed the icon(lib="fontawesome") implementation from a bundled copy of fontawesome, to the {fontawesome} package. This led to issue #3688, where icons that were previously working, were now breaking. That’s because {fontawesome} 0.3.0 and earlier did not have support for icon names used in Font Awesome 5 and earlier, only the newest icon names used in Font Awesome 6. Now, {fontawesome} 0.4.0 has restored support for those older icon names, and Shiny 1.7.2.1 has updated its {fontawesome} requirement to >=0.4.0.
```

So either upgrade to shiny 1.7.3 or downgrade shiny to < 1.7.0 seems to be solving this issue.
Feel free to give comments, I'll close this issue already as it seems not caused by code in this R package but in further downstream dependencies.

**Closed by jwijffels** 2022-11-08 22:22 UTC
